# Generated by Django 5.2.6 on 2025-09-11 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegisterPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="registers.register",
                    ),
                ),
            ],
            options={
                "unique_together": {("register", "date")},
            },
        ),
        migrations.CreateModel(
            name="CalibrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=100)),
                ("serial_no", models.CharField(max_length=100)),
                ("standard_used", models.CharField(max_length=100)),
                ("result", models.CharField(max_length=100)),
                ("tolerance", models.CharField(max_length=50)),
                ("calibrated_by", models.CharField(max_length=100)),
                ("verified_by", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_logs",
                        to="registers.registerpage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemperatureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=100)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("initials", models.CharField(max_length=10)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_logs",
                        to="registers.registerpage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WasteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("yellow_bags_no", models.PositiveIntegerField()),
                (
                    "yellow_bags_weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("yellow_bags_labeled", models.BooleanField(default=False)),
                ("sharps_containers_no", models.PositiveIntegerField()),
                (
                    "sharps_containers_weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("sharps_containers_labeled", models.BooleanField(default=False)),
                ("handed_over_by", models.CharField(max_length=100)),
                ("vehicle_no", models.CharField(max_length=50)),
                ("receiver_signature", models.CharField(max_length=100)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_logs",
                        to="registers.registerpage",
                    ),
                ),
            ],
        ),
    ]
